language: ruby

script: bundle exec rake travis

matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile-ruby-1.8.7

  allow_failures:
    - rvm: jruby-head

notifications:
  email: false

before_install:
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
